AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*_spec.rb'

Layout/DotPosition:
  EnforcedStyle: trailing

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/MixinUsage:
  Exclude:
    - 'spec/spec_helper.rb'
