language: ruby
rvm: 2.5.1
cache: bundler
sudo: false
before_install:
  - "echo '--colour' > ~/.rspec"
  - gem install bundler
  - gem update --system
install: bundle install
notifications:
  email: false
