name: CI

on:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  rspec:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
        - { ruby: 2.7 }
        - { ruby: '3.0' }
        - { ruby: 3.1 }
        - { ruby: 3.2 }

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: |
        bundle exec rspec
