name: RuboCop

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: rubocop
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Run RuboCop linter
      uses: reviewdog/action-rubocop@v2
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        rubocop_version: gemfile
        rubocop_extensions: rubocop-performance:gemfile rubocop-rspec:gemfile
